CC = /usr/bin/gcc
CXX = /usr/bin/g++
WINDRES = 
MOC = 
ASFLAGS = 
LDFLAGS = 
INCLUDE_DIRS = -I./deps/7zip
LIBRARY_DIRS = -L/usr/lib64
PACKAGE_NAME = retroarch
BUILD = 
PREFIX = /usr/local
HAVE_7ZIP = 1
HAVE_ACCESSIBILITY = 1
HAVE_AL = 0
ifneq ($(C89_BUILD),1)
HAVE_ALSA = 1
endif
ALSA_LIBS = -lasound
HAVE_ANGLE = 0
HAVE_AUDIOIO = 0
HAVE_AUDIOMIXER = 1
HAVE_AV_CHANNEL_LAYOUT = 0
HAVE_AVCODEC = 0
HAVE_AVDEVICE = 0
HAVE_AVFORMAT = 0
HAVE_AVUTIL = 0
HAVE_BLISSBOX = 0
HAVE_BLUETOOTH = 0
HAVE_BSV_MOVIE = 1
HAVE_BUILTINBEARSSL = 0
HAVE_BUILTINFLAC = 1
ifneq ($(C89_BUILD),1)
HAVE_BUILTINGLSLANG = 1
endif
ifneq ($(C89_BUILD),1)
HAVE_BUILTINMBEDTLS = 1
endif
HAVE_BUILTINZLIB = 1
HAVE_C99 = 1
C99_CFLAGS = -std=gnu99
HAVE_CACA = 0
HAVE_CC = 1
HAVE_CC_RESAMPLER = 1
HAVE_CDROM = 1
HAVE_CG = 0
ifneq ($(CXX_BUILD),1)
HAVE_CHD = 1
endif
HAVE_CHEATS = 1
HAVE_CHECK = 0
HAVE_CHEEVOS = 1
HAVE_COMMAND = 1
HAVE_CONFIGFILE = 1
HAVE_COREAUDIO3 = 0
HAVE_CORE_INFO_CACHE = 1
ifneq ($(C89_BUILD),1)
HAVE_CRTSWITCHRES = 1
endif
HAVE_CXX = 1
HAVE_CXX11 = 1
CXX11_CFLAGS = -std=c++11
HAVE_D3D8 = 0
HAVE_D3D9 = 0
HAVE_D3DX8 = 0
HAVE_D3DX9 = 0
HAVE_DBUS = 0
HAVE_DEBUG = 0
HAVE_DINPUT = 0
ifneq ($(C89_BUILD),1)
HAVE_DISCORD = 1
endif
HAVE_DISPMANX = 0
HAVE_DRM = 0
HAVE_DRMINGW = 0
HAVE_DR_MP3 = 1
HAVE_DSOUND = 0
HAVE_DSP_FILTER = 1
HAVE_DYLIB = 1
DYLIB_LIBS = -ldl
HAVE_DYNAMIC = 1
DYNAMIC_LIBS = -ldl
HAVE_DYNAMIC_EGL = 0
HAVE_EGL = 1
EGL_LIBS = -lEGL
HAVE_EXYNOS = 0
HAVE_FFMPEG = 0
HAVE_FLAC = 0
HAVE_FLOATHARD = 0
HAVE_FLOATSOFTFP = 0
HAVE_FONTCONFIG = 0
HAVE_FREETYPE = 1
FREETYPE_CFLAGS = -I/usr/include/freetype2 -I/usr/include/libpng16
FREETYPE_LIBS = -lfreetype
HAVE_GBM = 0
HAVE_GDI = 1
HAVE_GETADDRINFO = 1
GETADDRINFO_LIBS = -lc
HAVE_GETOPT_LONG = 1
GETOPT_LONG_LIBS = -lc
HAVE_GFX_WIDGETS = 1
HAVE_GLSL = 1
ifneq ($(C89_BUILD),1)
HAVE_GLSLANG = 1
endif
HAVE_GLSLANG_HLSL = 0
HAVE_GLSLANG_OGLCOMPILER = 0
HAVE_GLSLANG_OSDEPENDENT = 0
HAVE_GLSLANG_SPIRV = 0
HAVE_GLSLANG_SPIRV_TOOLS = 0
HAVE_GLSLANG_SPIRV_TOOLS_OPT = 0
HAVE_HID = 1
HAVE_HLSL = 0
HAVE_IBXM = 1
HAVE_IFINFO = 1
HAVE_IMAGEVIEWER = 1
HAVE_JACK = 0
HAVE_KMS = 0
HAVE_LANGEXTRA = 1
HAVE_LIBCHECK = 0
HAVE_LIBDECOR = 0
HAVE_LIBRETRODB = 1
HAVE_LIBSHAKE = 0
HAVE_LIBUSB = 0
HAVE_LUA = 0
HAVE_MALI_FBDEV = 0
HAVE_MEMFD_CREATE = 1
MEMFD_CREATE_LIBS = -lc
HAVE_MENU = 1
HAVE_METAL = 0
HAVE_MIST = 0
HAVE_MMAP = 1
MMAP_LIBS = -lc
HAVE_MOC = 0
HAVE_MPV = 0
HAVE_NEAREST_RESAMPLER = 1
HAVE_NEON = 0
HAVE_NETPLAYDISCOVERY = 1
HAVE_NETPLAYDISCOVERY = 1
HAVE_NETWORK_CMD = 1
ifneq ($(C89_BUILD),1)
HAVE_NETWORKGAMEPAD = 1
endif
HAVE_NETWORKING = 1
NETWORKING_LIBS = -lc
HAVE_NETWORK_VIDEO = 0
HAVE_NOUNUSED = 1
NOUNUSED_CFLAGS = -Wno-unused-result
HAVE_NOUNUSED_VARIABLE = 1
NOUNUSED_VARIABLE_CFLAGS = -Wno-unused-variable
HAVE_NVDA = 1
HAVE_ODROIDGO2 = 0
HAVE_OMAP = 0
HAVE_ONLINE_UPDATER = 1
HAVE_OPENDINGUX_FBDEV = 0
HAVE_OPENGL = 1
OPENGL_LIBS = -lGL
HAVE_OPENGL1 = 1
ifneq ($(C89_BUILD),1)
HAVE_OPENGL_CORE = 1
endif
HAVE_OPENGLES = 0
HAVE_OPENGLES3 = 0
HAVE_OPENGLES3_1 = 0
HAVE_OPENGLES3_2 = 0
HAVE_OPENSSL = 1
OPENSSL_LIBS = -lssl -lcrypto
HAVE_OSMESA = 0
HAVE_OSS = 1
HAVE_OSS_BSD = 0
HAVE_OSS_LIB = 0
HAVE_OVERLAY = 1
HAVE_PARPORT = 1
HAVE_PATCH = 1
HAVE_PLAIN_DRM = 0
HAVE_PRESERVE_DYLIB = 0
ifneq ($(C89_BUILD),1)
HAVE_PULSE = 1
endif
PULSE_CFLAGS = -D_REENTRANT
PULSE_LIBS = -lpulse
HAVE_QT = 0
HAVE_QT5CONCURRENT = 0
HAVE_QT5CORE = 0
HAVE_QT5GUI = 0
HAVE_QT5NETWORK = 0
HAVE_QT5WIDGETS = 0
HAVE_RBMP = 1
HAVE_REWIND = 1
HAVE_RJPEG = 1
HAVE_ROAR = 0
HAVE_RPILED = 1
HAVE_RPNG = 1
HAVE_RSOUND = 0
HAVE_RTGA = 1
HAVE_RUNAHEAD = 1
HAVE_RWAV = 1
HAVE_SAPI = 0
HAVE_SCREENSHOTS = 1
HAVE_SDL = 0
ifneq ($(C89_BUILD),1)
HAVE_SDL2 = 1
endif
SDL2_CFLAGS = -D_REENTRANT -I/usr/include/SDL2
SDL2_LIBS = -lSDL2
HAVE_SDL_DINGUX = 0
ifneq ($(C89_BUILD),1)
HAVE_SHADERPIPELINE = 1
endif
HAVE_SIXEL = 0
ifneq ($(C89_BUILD),1)
HAVE_SLANG = 1
endif
HAVE_SOCKET_LEGACY = 0
ifneq ($(C89_BUILD),1)
HAVE_SPIRV_CROSS = 1
endif
HAVE_SR2 = 1
HAVE_SSA = 0
HAVE_SSE = 0
ifneq ($(C89_BUILD),1)
HAVE_SSL = 1
endif
HAVE_STB_FONT = 1
HAVE_STB_IMAGE = 1
HAVE_STB_VORBIS = 1
HAVE_STDIN_CMD = 1
STDIN_CMD_LIBS = -lc
HAVE_STEAM = 0
HAVE_STRCASESTR = 1
STRCASESTR_LIBS = -lc
HAVE_SUNXI = 0
HAVE_SWRESAMPLE = 0
HAVE_SWSCALE = 0
HAVE_SYSTEMD = 0
HAVE_SYSTEMMBEDTLS = 0
HAVE_THREADS = 1
THREADS_LIBS = -lpthread
HAVE_THREAD_STORAGE = 1
THREAD_STORAGE_LIBS = -lpthread
HAVE_TINYALSA = 1
HAVE_TRANSLATE = 1
HAVE_UDEV = 1
UDEV_LIBS = -ludev
HAVE_UPDATE_ASSETS = 1
HAVE_UPDATE_CORES = 1
HAVE_V4L2 = 0
HAVE_VC_TEST = 0
HAVE_VG = 0
HAVE_VIDEOCORE = 0
HAVE_VIDEO_FILTER = 1
HAVE_VIDEO_LAYOUT = 1
HAVE_VIDEOPROCESSOR = 0
HAVE_VIVANTE_FBDEV = 0
HAVE_VULKAN = 0
HAVE_VULKAN_DISPLAY = 1
ifneq ($(C89_BUILD),1)
ifneq ($(CXX_BUILD),1)
HAVE_WAYLAND = 1
endif
endif
WAYLAND_LIBS = -lwayland-egl -lwayland-client
HAVE_WAYLAND_CURSOR = 1
WAYLAND_CURSOR_LIBS = -lwayland-cursor
HAVE_WAYLAND_PROTOS = 0
HAVE_WAYLAND_SCANNER = 1
HAVE_WIFI = 0
HAVE_WINRAWINPUT = 1
HAVE_X11 = 1
X11_LIBS = -lX11
HAVE_XCB = 1
XCB_LIBS = -lxcb
HAVE_XEXT = 1
XEXT_LIBS = -lXext
HAVE_XF86VM = 1
XF86VM_LIBS = -lXxf86vm
HAVE_XINERAMA = 1
XINERAMA_LIBS = -lXinerama
HAVE_XINPUT = 0
HAVE_XKBCOMMON = 1
XKBCOMMON_LIBS = -lxkbcommon
HAVE_XRANDR = 1
XRANDR_LIBS = -lXrandr
HAVE_XSHM = 1
HAVE_XVIDEO = 1
XVIDEO_LIBS = -lXv
HAVE_ZLIB = 1
ZLIB_LIBS = -lz
DATA_DIR = /usr/local/share
DYLIB_LIB = -ldl
ASSETS_DIR = /usr/local/share/retroarch
BIN_DIR = /usr/local/bin
DOC_DIR = /usr/local/share/doc/retroarch
MAN_DIR = /usr/local/share/man
OS = Linux
QT_VERSION = qt5
GLOBAL_CONFIG_DIR = /etc
